language: c
compiler:
  - clang
  - gcc

addons:
    apt:
        packages:
            - carton

before_install:
  # Fetch nginx source
  - wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar xvfz nginx-${NGINX_VERSION}.tar.gz
  - cd nginx-${NGINX_VERSION}

script:
  # Build nginx
  - ./configure --prefix=${TRAVIS_BUILD_DIR}/t/nginx --add-module=${TRAVIS_BUILD_DIR}
  - make
  - make install

  # Run tests
  - cd ${TRAVIS_BUILD_DIR}/t
  - ./restart.sh
  - carton install
  - carton exec ./ziptest.pl

env:
  - NGINX_VERSION="1.10.3"
  - NGINX_VERSION="1.11.13"
  - NGINX_VERSION="1.12.1"
  - NGINX_VERSION="1.13.5"
